# Generated by Django 5.2.3 on 2026-01-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_recommended_quantities_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
