# Generated by Django 5.2.1 on 2025-06-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_profile_old_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='commune',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
