# Generated by Django 5.2.3 on 2026-01-09 15:48

import payment.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='id_number',
            field=models.CharField(default='', help_text='Rut: 12345678-9', max_length=10, validators=[payment.validators.validar_rut]),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(default='', help_text='Rut: 12345678-9', max_length=10, validators=[payment.validators.validar_rut]),
        ),
    ]
