# Generated by Django 5.2.3 on 2025-10-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_brand_remove_product_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='height',
            new_name='height_cm',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='length',
            new_name='length_cm',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='volume',
            new_name='weight_kg',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='width_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.AddField(
            model_name='product',
            name='volume_m3',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
    ]
