# Generated by Django 5.2.3 on 2025-12-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_international_items',
            field=models.BooleanField(default=False),
        ),
    ]
