# Generated by Django 5.2.1 on 2025-06-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_shippingaddress_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='commune',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
