# Generated by Django 5.2.3 on 2025-12-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_has_international_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_international',
            field=models.BooleanField(default=False),
        ),
    ]
