# Generated by Django 5.2.3 on 2025-12-17 20:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_orderitem_is_international'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name_plural': 'Shipping Addresses'},
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_address1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_address2',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_city',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_phone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_commune',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_email',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_full_name',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_state',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_zipcode',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(default='Santiago', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='Chile', max_length=100),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(default='ralzola@miuandes.cl', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
