# Generated by Django 5.2.3 on 2025-12-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_shippingaddress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='notes',
            field=models.TextField(blank=True, help_text='Ej: "Dejar con conserje", "Timbre no funciona", "Casa blanca con reja negra"', max_length=300, null=True, verbose_name='Comentarios adicionales'),
        ),
    ]
