# Generated by Django 5.2.1 on 2025-06-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_address1_shippingaddress_shipping_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
