# Generated by Django 5.2.3 on 2025-12-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_shippingaddress_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='region',
            field=models.CharField(default='RM', max_length=100),
            preserve_default=False,
        ),
    ]
