# Generated by Django 5.2.3 on 2025-12-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_order_options_order_accounting_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='commerce_code',
        ),
        migrations.AlterField(
            model_name='order',
            name='buy_order',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
