# Generated by Django 5.2.3 on 2026-01-09 15:48

import payment.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_remove_order_commerce_code_alter_order_buy_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_number',
            field=models.CharField(default='', help_text='Formato: 12345678-9', max_length=10, validators=[payment.validators.validar_rut]),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='id_number',
            field=models.CharField(default='', help_text='Formato: 12345678-9', max_length=10, validators=[payment.validators.validar_rut]),
        ),
    ]
