# Generated by Django 5.2.3 on 2026-01-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_coupon_order_amount_before_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('shipped', 'Enviado'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('transbank', 'Transbank'), ('bank_transfer', 'Transferencia Bancaria')], default='transbank', max_length=20),
        ),
    ]
