# Generated by Django 5.2.3 on 2026-01-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='id_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
